sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO="1.11"
  - DJANGO="2.1"
  - DJANGO="2.2"
  - DJANGO="3.0"
  - DJANGO="master"
matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.1"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="2.2"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="3.0"
    - python: "3.7"
      sudo: required
      dist: xenial
      env: DJANGO="master"
    - python: "3.8"
      sudo: required
      dist: xenial
      env: DJANGO="2.2"
    - python: "3.8"
      sudo: required
      dist: xenial
      env: DJANGO="3.0"
  allow_failures:
    - python: "3.5"
      env: DJANGO="master"
    - python: "3.6"
      env: DJANGO="master"
    - python: "3.7"
      env: DJANGO="master"
  exclude:
    - python: "2.7"
      env: DJANGO="2.1"
    - python: "2.7"
      env: DJANGO="master"
    - python: "3.5"
      env: DJANGO="3.0"
after_success: codecov
install: pip install tox-travis codecov
script: tox
